"""empty message

Revision ID: 2e61f019a7f4
Revises: 395c7e8ada13
Create Date: 2026-03-10 19:09:24.076733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e61f019a7f4'
down_revision: Union[str, Sequence[str], None] = '395c7e8ada13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_duration', sa.Column('latest', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_duration', 'latest')
    # ### end Alembic commands ###
