"""empty message

Revision ID: a2a2cb6083b2
Revises: 2e61f019a7f4
Create Date: 2026-03-10 20:00:28.379528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a2cb6083b2'
down_revision: Union[str, Sequence[str], None] = '2e61f019a7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_day_off', sa.Boolean(), nullable=False, ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_day_off')
    # ### end Alembic commands ###
